"""Omakase backend.

A FastAPI service that turns a user's interests into short, social-media style
posts generated by Gemini (see `GEMINI_MODEL`), streamed back to the client via
Server-Sent Events (SSE).

Run locally:

    uvicorn main:app --reload --host 0.0.0.0 --port 8000

The iOS client connects to `POST /feed/stream` and reads SSE events as they
arrive, giving a real-time typing effect in the feed.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import uuid
from typing import AsyncIterator

import google.generativeai as genai
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field, field_validator

load_dotenv()

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("omakase")

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
# Default matches current AI Studio model IDs; `gemini-1.5-flash` often 404s on v1beta now.
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)
else:
    logger.warning("GEMINI_API_KEY is not set. The /feed/stream endpoint will return an error until it is configured.")


app = FastAPI(title="Omakase", version="0.1.0")

# The iOS app talks to the backend directly, so CORS is mainly useful for
# browser-based debugging. Keep it permissive for local development.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


class FeedRequest(BaseModel):
    """Payload sent by the iOS client to request a single generated post."""

    interests: list[str] = Field(
        default_factory=list,
        description="Free-form user interests, e.g. ['David Fincher', 'Aftersun', 'Secret Hitler'].",
    )
    seen_count: int = Field(
        default=0,
        description="Number of posts already shown; used to nudge the model toward variety.",
    )
    language: str = Field(
        default="en",
        description="BCP-47 language tag for model output (e.g. en, tr). Unknown values fall back to English.",
    )

    @field_validator("language")
    @classmethod
    def _normalize_language(cls, v: str) -> str:
        s = (v or "en").strip().lower()
        if s not in ("en", "tr"):
            return "en"
        return s


class SuggestRequest(BaseModel):
    """Payload for the interest-suggestion endpoint."""

    interests: list[str] = Field(
        default_factory=list,
        description="Interests the user has already added or is currently typing.",
    )
    draft: str = Field(
        default="",
        description="Partial text the user is typing right now (may be empty).",
    )
    exclude_suggestions: list[str] = Field(
        default_factory=list,
        description="Suggestions already shown; the model must not repeat these.",
    )
    language: str = Field(
        default="en",
        description="BCP-47 language tag for suggestion strings (en or tr).",
    )

    @field_validator("language")
    @classmethod
    def _normalize_language_suggest(cls, v: str) -> str:
        s = (v or "en").strip().lower()
        if s not in ("en", "tr"):
            return "en"
        return s


SYSTEM_PROMPT = (
    "You are the voice of Omakase — a charismatic, well-read curator who loves "
    "surprising people with things they didn't know they needed to know. "
    "Every post you write has personality: it's funny, sharp, or delightfully weird. "
    "You MUST output exactly two parts:\n"
    "1) The first line ONLY must be: TITLE: <a short, specific headline for THIS post, max 8 words> "
    "(no quotes around the title).\n"
    "2) Starting on the next line, write the post body: ONE short, self-contained piece (40-90 words) "
    "like a banger tweet from a very smart friend.\n"
    "The title must preview the body; do not use a generic label. Do not repeat 'TITLE' or the headline "
    "inside the body. Avoid hashtags, emoji, and meta commentary. "
    "Do not greet the reader. Do not mention that you are an AI."
)


def _feed_language_instruction(language: str) -> str:
    """Tells the model which natural language to use for TITLE line and body."""
    if language == "tr":
        return (
            "LANGUAGE: Write the entire post in Turkish (Türkçe). "
            "Both the TITLE: headline (after the prefix TITLE: ) and every word of the body must be Turkish. "
            "Keep the literal ASCII prefix TITLE: on the first line."
        )
    return (
        "LANGUAGE: Write the entire post in English. "
        "Both the TITLE: headline (after the prefix TITLE: ) and the body must be English."
    )


def _feed_system_instruction(language: str) -> str:
    return SYSTEM_PROMPT + "\n\n" + _feed_language_instruction(language)

# Rotating format templates. The user prompt picks one based on seen_count so
# back-to-back posts always feel structurally different.
_POST_FORMATS = [
    (
        "FUN FACT DROP",
        "Share one genuinely surprising, little-known fact related to the user's interests. "
        "Start with the fact itself — don't say 'Fun fact:'. Make it feel like you just "
        "couldn't help sharing it. End with a punchy one-liner observation.",
    ),
    (
        "HOT TAKE",
        "Give a bold, slightly controversial opinion about something in the user's interest space. "
        "Be confident, not obnoxious. Make the reader nod or loudly disagree — either is a win.",
    ),
    (
        "RABBIT HOLE ALERT",
        "Tease a fascinating deep-dive topic connected to the user's interests. "
        "Write like you just fell down this rabbit hole at 2am and you need to tell someone. "
        "Be specific — name the thing, the person, the event, or the phenomenon.",
    ),
    (
        "UNLIKELY CONNECTION",
        "Find a surprising, counterintuitive connection between two things in the user's interest world. "
        "The weirder and more accurate the link, the better. Make the reader think 'wait, really?'",
    ),
    (
        "TINY RECOMMENDATION",
        "Give one very specific recommendation (a scene, a chapter, a moment, a dish, a technique, "
        "a detail) that most people overlook. Be precise enough that it feels like insider knowledge.",
    ),
    (
        "REFRAME",
        "Take something familiar from the user's interests and show it from a completely unexpected angle. "
        "Flip the conventional wisdom. The reader should feel like they'll never see it the same way again.",
    ),
    (
        "THE THING NOBODY TALKS ABOUT",
        "Surface an underrated, overlooked, or unfairly forgotten thing — a person, work, moment, or idea — "
        "related to the user's interests. Write with genuine enthusiasm, like you're righting a wrong.",
    ),
    (
        "CURSED TRIVIA",
        "Share a piece of trivia that is so odd, ironic, or absurd that it's almost offensive to know. "
        "Keep it true and accurate. Write with dry humor.",
    ),
]


def _build_user_prompt(interests: list[str], seen_count: int, language: str) -> str:
    cleaned = [i.strip() for i in interests if i and i.strip()]
    if not cleaned:
        taste = "someone with eclectic, thoughtful taste in culture"
    else:
        taste = "someone who cares about: " + ", ".join(cleaned)

    format_name, format_instruction = _POST_FORMATS[seen_count % len(_POST_FORMATS)]

    follow_lang = ""
    if language == "tr":
        follow_lang = (
            "Uyarı: Gönderiyi mutlaka Türkçe yaz. Aşağıdaki İngilizce format adı ve talimatlar "
            "sadece yapı için; çıktı tamamen Türkçe olmalı.\n\n"
        )

    return (
        follow_lang
        + f"Write a post for {taste}.\n"
        f"Post index in this session: {seen_count}.\n"
        f"\nFORMAT THIS POST AS: {format_name}\n"
        f"Instructions for this format: {format_instruction}\n"
        "\nThe post must feel human, specific, and entertaining — never generic or lecture-y. "
        "Do NOT label the format in the post itself."
    )


_TITLE_LINE = re.compile(r"(?i)^TITLE:\s*(.+)$")


# Gemini often emits the entire post body in one stream delta. Clients expect multiple small
# `token` SSE events so the Swift UI can animate like Gemini in the browser.
_SPLIT_STREAM_SOFT_CAP = 40


def _split_fragment_for_smooth_stream(fragment: str, *, max_piece: int = _SPLIT_STREAM_SOFT_CAP) -> list[str]:
    """Split large model deltas into modest substrings, preferring word boundaries."""
    if not fragment:
        return []
    if len(fragment) <= max_piece:
        return [fragment]
    chunks: list[str] = []
    idx = 0
    fragment_len = len(fragment)
    min_wordish = max(6, max_piece // 4)
    while idx < fragment_len:
        end = min(idx + max_piece, fragment_len)
        if end >= fragment_len:
            tail = fragment[idx:]
            if tail:
                chunks.append(tail)
            break
        window = fragment[idx:end]
        cut = window.rfind(" ")
        if cut >= min_wordish:
            end = idx + cut + 1
        chunks.append(fragment[idx:end])
        idx = end
    return chunks if chunks else [fragment]


def _enqueue_stream_body_fragment(
    loop: asyncio.AbstractEventLoop,
    queue: asyncio.Queue,
    fragment: str,
) -> None:
    for piece in _split_fragment_for_smooth_stream(fragment):
        loop.call_soon_threadsafe(queue.put_nowait, ("token", piece))


def _feed_tokens_from_stream_chunks(response: object, queue: asyncio.Queue, loop: asyncio.AbstractEventLoop) -> None:
    """Turn Gemini stream chunks into queue items; emits ('title', str) then body ('token', str)."""
    carry = ""
    title_done = False
    for chunk in response:
        text = _stream_chunk_text(chunk)
        if not text:
            continue
        carry += text
        if not title_done:
            if "\n" not in carry:
                continue
            first_line, carry = carry.split("\n", 1)
            m = _TITLE_LINE.match(first_line.strip())
            if m:
                loop.call_soon_threadsafe(
                    queue.put_nowait,
                    ("title", m.group(1).strip()),
                )
            else:
                carry = first_line + "\n" + carry
            title_done = True
        if carry:
            _enqueue_stream_body_fragment(loop, queue, carry)
            carry = ""
    if not title_done and carry:
        loop.call_soon_threadsafe(queue.put_nowait, ("token", carry))
    elif title_done and carry:
        _enqueue_stream_body_fragment(loop, queue, carry)


def _stream_chunk_text(chunk: object) -> str:
    """Best-effort text from a streaming chunk (Gemini SDK quirks vary by chunk)."""
    try:
        t = getattr(chunk, "text", None)
        if t:
            return str(t)
    except (ValueError, AttributeError):
        pass
    try:
        cands = getattr(chunk, "candidates", None) or []
        if not cands:
            return ""
        content = getattr(cands[0], "content", None)
        parts = getattr(content, "parts", None) if content is not None else None
        if not parts:
            return ""
        pieces: list[str] = []
        for part in parts:
            txt = getattr(part, "text", None)
            if txt:
                pieces.append(str(txt))
        return "".join(pieces)
    except (IndexError, AttributeError, TypeError):
        return ""


def _sse_event(data: dict, *, event: str | None = None) -> str:
    """Format a payload as a single SSE frame."""
    lines: list[str] = []
    if event:
        lines.append(f"event: {event}")
    lines.append(f"data: {json.dumps(data, ensure_ascii=False)}")
    lines.append("")
    lines.append("")
    return "\n".join(lines)


async def _stream_post(interests: list[str], seen_count: int, language: str) -> AsyncIterator[str]:
    """Yield SSE frames for one generated post."""
    post_id = str(uuid.uuid4())
    yield _sse_event({"id": post_id}, event="start")

    if not GEMINI_API_KEY:
        yield _sse_event(
            {"message": "Server is missing GEMINI_API_KEY. See backend/README.md."},
            event="error",
        )
        return

    model = genai.GenerativeModel(
        model_name=GEMINI_MODEL,
        system_instruction=_feed_system_instruction(language),
    )
    prompt = _build_user_prompt(interests, seen_count, language)

    try:
        # google-generativeai's streaming API is synchronous; run it in a
        # worker thread and bridge each chunk to the async generator.
        queue: asyncio.Queue[tuple[str, object]] = asyncio.Queue()
        loop = asyncio.get_running_loop()

        def _produce() -> None:
            try:
                response = model.generate_content(prompt, stream=True)
                _feed_tokens_from_stream_chunks(response, queue, loop)
                loop.call_soon_threadsafe(queue.put_nowait, ("done", None))
            except Exception as exc:  # noqa: BLE001 — funnel any SDK error to the client
                loop.call_soon_threadsafe(queue.put_nowait, ("error", exc))

        producer = asyncio.create_task(asyncio.to_thread(_produce))

        saw_any_output = False
        saw_error = False
        while True:
            kind, payload = await queue.get()
            if kind == "token":
                saw_any_output = True
                yield _sse_event({"text": payload}, event="token")
            elif kind == "title":
                saw_any_output = True
                yield _sse_event({"title": str(payload)}, event="title")
            elif kind == "done":
                break
            elif kind == "error":
                saw_error = True
                logger.exception("Gemini streaming failed", exc_info=payload)
                yield _sse_event({"message": str(payload)}, event="error")
                break

        await producer

        if not saw_any_output and not saw_error:
            yield _sse_event(
                {
                    "message": (
                        "The model returned no text. Check GEMINI_MODEL in .env "
                        f"(currently {GEMINI_MODEL!r}), API quota, and that the key is valid."
                    )
                },
                event="error",
            )

    except asyncio.CancelledError:
        # Client disconnected — just stop.
        logger.info("Client disconnected from stream %s", post_id)
        raise

    yield _sse_event({"id": post_id}, event="done")


def _generative_response_text(response: object) -> str:
    """Best-effort plain text from google-generativeai (handles blocked / multi-part replies)."""
    try:
        text = response.text  # type: ignore[attr-defined]
        if isinstance(text, str) and text.strip():
            return text.strip()
    except Exception:  # noqa: BLE001 — SDK raises if no parts / blocked
        pass
    candidates = getattr(response, "candidates", None) or []
    if not candidates:
        return ""
    parts_out: list[str] = []
    for cand in candidates:
        content = getattr(cand, "content", None)
        parts = getattr(content, "parts", None) if content is not None else None
        if not parts:
            continue
        for part in parts:
            t = getattr(part, "text", None)
            if isinstance(t, str) and t:
                parts_out.append(t)
    return "".join(parts_out).strip()


def _parse_suggestion_strings(raw: str) -> list[str]:
    """Parse model output into a list of suggestion strings (JSON array, with fallbacks)."""
    s = raw.strip()
    s = s.removeprefix("```json").removeprefix("```").removesuffix("```").strip()

    def _loads_list(payload: str) -> list[str]:
        data = json.loads(payload)
        if not isinstance(data, list):
            raise ValueError("Model did not return a JSON array.")
        return [str(x) for x in data if x]

    try:
        return _loads_list(s)
    except (json.JSONDecodeError, ValueError, TypeError):
        pass

    # Model wrapped the array in prose; take the first [...] block.
    start = s.find("[")
    end = s.rfind("]")
    if start != -1 and end > start:
        try:
            return _loads_list(s[start : end + 1])
        except (json.JSONDecodeError, ValueError, TypeError):
            pass

    # Last resort: double-quoted strings on their own lines.
    quoted = re.findall(r'"([^"\\]*(?:\\.[^"\\]*)*)"', s)
    if len(quoted) >= 3:
        return quoted[:10]

    raise ValueError(f"Could not parse suggestions from model output (first 200 chars): {s[:200]!r}")


_SUGGEST_SYSTEM = (
    "You are an interest-discovery assistant. Given a list of things a user already cares about "
    "(and optionally a partial search term they are typing), suggest NEW interests they might enjoy. "
    "Follow these rules strictly:\n"
    "1. Return ONLY a JSON array of strings — no markdown, no explanation, no extra keys.\n"
    "2. Return exactly 7 suggestions.\n"
    "3. About 4 of the 7 should be closely related to what the user already listed.\n"
    "4. The remaining 3 should be surprising, lateral, or from an adjacent domain — things the user "
    "probably hasn't considered but might love once they discover them.\n"
    "5. Never repeat an interest the user already has, nor any item listed as an excluded suggestion.\n"
    "6. Keep each suggestion short: 1-4 words, title-cased.\n"
    "7. Prioritise specificity over genre labels (e.g. prefer 'Wong Kar-wai' over 'Arthouse Cinema')."
)


def _suggest_system_for_language(language: str) -> str:
    lang_rule = (
        "8. Write all 7 strings in natural Turkish (Türkçe), using culturally normal spelling and "
        "title-style capitalization suitable for Turkish."
        if language == "tr"
        else "8. Write all 7 strings in English."
    )
    return _SUGGEST_SYSTEM + "\n" + lang_rule


@app.post("/interests/suggest")
async def interests_suggest(req: SuggestRequest) -> dict:
    """Return ~7 AI-generated interest suggestions based on what the user already has.

    Response: ``{ "suggestions": ["...", ...] }``
    """
    if not GEMINI_API_KEY:
        raise HTTPException(status_code=503, detail="Server is missing GEMINI_API_KEY.")

    existing = [i.strip() for i in req.interests if i.strip()]
    draft = req.draft.strip()
    excluded = [s.strip() for s in req.exclude_suggestions if s.strip()]

    parts: list[str] = []
    if existing:
        parts.append("Interests already added: " + ", ".join(existing) + ".")
    if draft:
        parts.append(f'The user is currently typing: "{draft}".  '
                     "Include suggestions related to this term as well.")
    if not parts:
        parts.append("The user hasn't added any interests yet. Suggest a diverse, intriguing starter set.")
    if excluded:
        parts.append(
            "These ideas were already shown — suggest 7 completely different ones (do not repeat or "
            "minorly rephrase): " + ", ".join(excluded) + "."
        )

    lang_code = req.language

    user_prompt = " ".join(parts) + "\n\nRespond with a JSON array only."

    model = genai.GenerativeModel(
        model_name=GEMINI_MODEL,
        system_instruction=_suggest_system_for_language(lang_code),
    )

    try:
        response = await asyncio.to_thread(
            model.generate_content,
            user_prompt,
            # No streaming needed — we want a fast, small response.
        )
        raw = _generative_response_text(response)
        if not raw:
            fr = None
            if getattr(response, "candidates", None):
                fr = getattr(response.candidates[0], "finish_reason", None)
            logger.warning("Interest suggestion: empty model text (finish_reason=%s)", fr)
            raise ValueError("Model returned no text (blocked, empty, or unsupported response).")
        suggestions = _parse_suggestion_strings(raw)[:10]
    except Exception as exc:  # noqa: BLE001
        logger.warning("Interest suggestion failed: %s", exc)
        raise HTTPException(status_code=502, detail=f"Suggestion generation failed: {exc}") from exc

    return {"suggestions": suggestions}


@app.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok", "model": GEMINI_MODEL, "has_api_key": str(bool(GEMINI_API_KEY))}


@app.post("/feed/stream")
async def feed_stream(req: FeedRequest) -> StreamingResponse:
    """Stream a single generated post as Server-Sent Events.

    The response is `text/event-stream` with event types:

    - `start` — `{ "id": "<uuid>" }` signals a new post
    - `title` — `{ "title": "<headline>" }` once, parsed from the model's `TITLE:` line
    - `token` — `{ "text": "<delta>" }` for each body chunk (title line is not repeated here)
    - `done`  — `{ "id": "<uuid>" }` signals the post is complete

    On failure an `error` event is emitted with a human-readable message.
    """
    if len(req.interests) > 50:
        raise HTTPException(status_code=400, detail="Too many interests (max 50).")

    headers = {
        "Cache-Control": "no-cache",
        "Connection": "keep-alive",
        # Disable buffering on common reverse proxies.
        "X-Accel-Buffering": "no",
    }
    return StreamingResponse(
        _stream_post(req.interests, req.seen_count, req.language),
        media_type="text/event-stream",
        headers=headers,
    )
