"""Omakase backend.

A FastAPI service that turns a user's interests into short, social-media style
posts generated by Gemini (see `GEMINI_MODEL`), streamed back to the client via
Server-Sent Events (SSE).

Run locally:

    uvicorn main:app --reload --host 0.0.0.0 --port 8000

The iOS client connects to `POST /feed/stream` and reads SSE events as they
arrive, giving a real-time typing effect in the feed.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import uuid
from typing import AsyncIterator

import google.generativeai as genai
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

load_dotenv()

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("omakase")

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
# Default matches current AI Studio model IDs; `gemini-1.5-flash` often 404s on v1beta now.
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)
else:
    logger.warning("GEMINI_API_KEY is not set. The /feed/stream endpoint will return an error until it is configured.")


app = FastAPI(title="Omakase", version="0.1.0")

# The iOS app talks to the backend directly, so CORS is mainly useful for
# browser-based debugging. Keep it permissive for local development.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


class FeedRequest(BaseModel):
    """Payload sent by the iOS client to request a single generated post."""

    interests: list[str] = Field(
        default_factory=list,
        description="Free-form user interests, e.g. ['David Fincher', 'Aftersun', 'Secret Hitler'].",
    )
    seen_count: int = Field(
        default=0,
        description="Number of posts already shown; used to nudge the model toward variety.",
    )


SYSTEM_PROMPT = (
    "You are the voice of Omakase — a charismatic, well-read curator who loves "
    "surprising people with things they didn't know they needed to know. "
    "Every post you write has personality: it's funny, sharp, or delightfully weird. "
    "Write ONE short, self-contained post (40-90 words) that feels like a banger tweet "
    "from a very smart friend. Avoid hashtags, emoji, and meta commentary. "
    "Do not greet the reader. Do not mention that you are an AI. "
    "Start directly with the post content."
)

# Rotating format templates. The user prompt picks one based on seen_count so
# back-to-back posts always feel structurally different.
_POST_FORMATS = [
    (
        "FUN FACT DROP",
        "Share one genuinely surprising, little-known fact related to the user's interests. "
        "Start with the fact itself — don't say 'Fun fact:'. Make it feel like you just "
        "couldn't help sharing it. End with a punchy one-liner observation.",
    ),
    (
        "HOT TAKE",
        "Give a bold, slightly controversial opinion about something in the user's interest space. "
        "Be confident, not obnoxious. Make the reader nod or loudly disagree — either is a win.",
    ),
    (
        "RABBIT HOLE ALERT",
        "Tease a fascinating deep-dive topic connected to the user's interests. "
        "Write like you just fell down this rabbit hole at 2am and you need to tell someone. "
        "Be specific — name the thing, the person, the event, or the phenomenon.",
    ),
    (
        "UNLIKELY CONNECTION",
        "Find a surprising, counterintuitive connection between two things in the user's interest world. "
        "The weirder and more accurate the link, the better. Make the reader think 'wait, really?'",
    ),
    (
        "TINY RECOMMENDATION",
        "Give one very specific recommendation (a scene, a chapter, a moment, a dish, a technique, "
        "a detail) that most people overlook. Be precise enough that it feels like insider knowledge.",
    ),
    (
        "REFRAME",
        "Take something familiar from the user's interests and show it from a completely unexpected angle. "
        "Flip the conventional wisdom. The reader should feel like they'll never see it the same way again.",
    ),
    (
        "THE THING NOBODY TALKS ABOUT",
        "Surface an underrated, overlooked, or unfairly forgotten thing — a person, work, moment, or idea — "
        "related to the user's interests. Write with genuine enthusiasm, like you're righting a wrong.",
    ),
    (
        "CURSED TRIVIA",
        "Share a piece of trivia that is so odd, ironic, or absurd that it's almost offensive to know. "
        "Keep it true and accurate. Write with dry humor.",
    ),
]


def _build_user_prompt(interests: list[str], seen_count: int) -> str:
    cleaned = [i.strip() for i in interests if i and i.strip()]
    if not cleaned:
        taste = "someone with eclectic, thoughtful taste in culture"
    else:
        taste = "someone who cares about: " + ", ".join(cleaned)

    format_name, format_instruction = _POST_FORMATS[seen_count % len(_POST_FORMATS)]

    return (
        f"Write a post for {taste}.\n"
        f"Post index in this session: {seen_count}.\n"
        f"\nFORMAT THIS POST AS: {format_name}\n"
        f"Instructions for this format: {format_instruction}\n"
        "\nThe post must feel human, specific, and entertaining — never generic or lecture-y. "
        "Do NOT label the format in the post itself."
    )


def _stream_chunk_text(chunk: object) -> str:
    """Best-effort text from a streaming chunk (Gemini SDK quirks vary by chunk)."""
    try:
        t = getattr(chunk, "text", None)
        if t:
            return str(t)
    except (ValueError, AttributeError):
        pass
    try:
        cands = getattr(chunk, "candidates", None) or []
        if not cands:
            return ""
        content = getattr(cands[0], "content", None)
        parts = getattr(content, "parts", None) if content is not None else None
        if not parts:
            return ""
        pieces: list[str] = []
        for part in parts:
            txt = getattr(part, "text", None)
            if txt:
                pieces.append(str(txt))
        return "".join(pieces)
    except (IndexError, AttributeError, TypeError):
        return ""


def _sse_event(data: dict, *, event: str | None = None) -> str:
    """Format a payload as a single SSE frame."""
    lines: list[str] = []
    if event:
        lines.append(f"event: {event}")
    lines.append(f"data: {json.dumps(data, ensure_ascii=False)}")
    lines.append("")
    lines.append("")
    return "\n".join(lines)


async def _stream_post(interests: list[str], seen_count: int) -> AsyncIterator[str]:
    """Yield SSE frames for one generated post."""
    post_id = str(uuid.uuid4())
    yield _sse_event({"id": post_id}, event="start")

    if not GEMINI_API_KEY:
        yield _sse_event(
            {"message": "Server is missing GEMINI_API_KEY. See backend/README.md."},
            event="error",
        )
        return

    model = genai.GenerativeModel(
        model_name=GEMINI_MODEL,
        system_instruction=SYSTEM_PROMPT,
    )
    prompt = _build_user_prompt(interests, seen_count)

    try:
        # google-generativeai's streaming API is synchronous; run it in a
        # worker thread and bridge each chunk to the async generator.
        queue: asyncio.Queue[tuple[str, object]] = asyncio.Queue()
        loop = asyncio.get_running_loop()

        def _produce() -> None:
            try:
                response = model.generate_content(prompt, stream=True)
                for chunk in response:
                    text = _stream_chunk_text(chunk)
                    if text:
                        loop.call_soon_threadsafe(queue.put_nowait, ("token", text))
                loop.call_soon_threadsafe(queue.put_nowait, ("done", None))
            except Exception as exc:  # noqa: BLE001 — funnel any SDK error to the client
                loop.call_soon_threadsafe(queue.put_nowait, ("error", exc))

        producer = asyncio.create_task(asyncio.to_thread(_produce))

        saw_token = False
        saw_error = False
        while True:
            kind, payload = await queue.get()
            if kind == "token":
                saw_token = True
                yield _sse_event({"text": payload}, event="token")
            elif kind == "done":
                break
            elif kind == "error":
                saw_error = True
                logger.exception("Gemini streaming failed", exc_info=payload)
                yield _sse_event({"message": str(payload)}, event="error")
                break

        await producer

        if not saw_token and not saw_error:
            yield _sse_event(
                {
                    "message": (
                        "The model returned no text. Check GEMINI_MODEL in .env "
                        f"(currently {GEMINI_MODEL!r}), API quota, and that the key is valid."
                    )
                },
                event="error",
            )

    except asyncio.CancelledError:
        # Client disconnected — just stop.
        logger.info("Client disconnected from stream %s", post_id)
        raise

    yield _sse_event({"id": post_id}, event="done")


@app.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok", "model": GEMINI_MODEL, "has_api_key": str(bool(GEMINI_API_KEY))}


@app.post("/feed/stream")
async def feed_stream(req: FeedRequest) -> StreamingResponse:
    """Stream a single generated post as Server-Sent Events.

    The response is `text/event-stream` with three event types:

    - `start` — `{ "id": "<uuid>" }` signals a new post
    - `token` — `{ "text": "<delta>" }` for each text chunk from Gemini
    - `done`  — `{ "id": "<uuid>" }` signals the post is complete

    On failure an `error` event is emitted with a human-readable message.
    """
    if len(req.interests) > 50:
        raise HTTPException(status_code=400, detail="Too many interests (max 50).")

    headers = {
        "Cache-Control": "no-cache",
        "Connection": "keep-alive",
        # Disable buffering on common reverse proxies.
        "X-Accel-Buffering": "no",
    }
    return StreamingResponse(
        _stream_post(req.interests, req.seen_count),
        media_type="text/event-stream",
        headers=headers,
    )
