"""Omakase backend.

A FastAPI service that turns a user's interests into short, social-media style
posts generated by Gemini (see `GEMINI_MODEL`), streamed back to the client via
Server-Sent Events (SSE).

Run locally:

    uvicorn main:app --reload --host 0.0.0.0 --port 8000

The iOS client connects to `POST /feed/stream` and reads SSE events as they
arrive, giving a real-time typing effect in the feed.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import uuid
import xml.etree.ElementTree as ET
from typing import AsyncIterator, Optional
from urllib.request import Request, urlopen
from urllib.error import HTTPError, URLError

from google import genai
from google.genai import types
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field, field_validator

load_dotenv()

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("omakase")

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
# gemini-3.5-flash is used for feed posts: no thinking phase → instant token streaming.
# gemini-3.1-pro-preview is kept for deep dives where quality/depth matters more than latency.
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-3.5-flash")
GEMINI_DEEP_DIVE_MODEL = os.getenv("GEMINI_DEEP_DIVE_MODEL", "gemini-3.1-pro-preview")
GEMINI_SUGGEST_MODEL = os.getenv("GEMINI_SUGGEST_MODEL", "gemini-3.1-flash-lite")

if GEMINI_API_KEY:
    genai_client = genai.Client(api_key=GEMINI_API_KEY)
else:
    logger.warning("GEMINI_API_KEY is not set. The /feed/stream endpoint will return an error until it is configured.")


app = FastAPI(title="Omakase", version="0.1.0")

# The iOS app talks to the backend directly, so CORS is mainly useful for
# browser-based debugging. Keep it permissive for local development.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


class FeedRequest(BaseModel):
    """Payload sent by the iOS client to request a single generated post."""

    interests: list[str] = Field(
        default_factory=list,
        description="Free-form user interests, e.g. ['David Fincher', 'Aftersun', 'Secret Hitler'].",
    )
    seen_count: int = Field(
        default=0,
        description="Number of posts already shown; used to nudge the model toward variety.",
    )
    language: str = Field(
        default="en",
        description="BCP-47 language tag for model output (e.g. en, tr). Unknown values fall back to English.",
    )
    letterboxd_films: Optional[list[dict]] = Field(
        default=None,
        description=(
            "Optional list of recently watched films from Letterboxd. "
            "Each dict has keys: title, year, rating (0-5), watched_date."
        ),
    )

    @field_validator("language")
    @classmethod
    def _normalize_language(cls, v: str) -> str:
        s = (v or "en").strip().lower()
        if s not in ("en", "tr"):
            return "en"
        return s


class SuggestRequest(BaseModel):
    """Payload for the interest-suggestion endpoint."""

    interests: list[str] = Field(
        default_factory=list,
        description="Interests the user has already added or is currently typing.",
    )
    draft: str = Field(
        default="",
        description="Partial text the user is typing right now (may be empty).",
    )
    exclude_suggestions: list[str] = Field(
        default_factory=list,
        description="Suggestions already shown; the model must not repeat these.",
    )
    language: str = Field(
        default="en",
        description="BCP-47 language tag for suggestion strings (en or tr).",
    )

    @field_validator("language")
    @classmethod
    def _normalize_language_suggest(cls, v: str) -> str:
        s = (v or "en").strip().lower()
        if s not in ("en", "tr"):
            return "en"
        return s


class DeepDiveRequest(BaseModel):
    """Payload sent by the iOS client to request a deep-dive expansion of a post."""

    original_title: str
    original_text: str
    interests: list[str] = Field(..., max_length=50)
    language: str = "en"

    @field_validator("language")
    @classmethod
    def _check_lang(cls, v: str) -> str:
        if v not in ("en", "tr"):
            raise ValueError("language must be 'en' or 'tr'")
        return v


SYSTEM_PROMPT = (
    "You are the voice of Omakase — an expert curator dedicated to surfacing "
    "high-density, niche information. You avoid generalities, 'fluff', and meta-commentary. "
    "Your primary goal is for the user to learn something concrete and surprising "
    "in every single post. While you remain charismatic and sharp, you prioritize "
    "facts, specific details, and non-obvious data over vague opinions or personal takes.\n"
    "You MUST output exactly three parts, each on its own line:\n"
    "1) The first line ONLY must be: TITLE: <a short, specific headline for THIS post, max 8 words> "
    "(no quotes around the title).\n"
    "2) The second line ONLY must be: TAGS: <comma-separated list of user interests this post relates to>. "
    "Pick ONLY from the interests the user provided — do not invent new tags. "
    "Usually 1-3 tags. If the post bridges multiple interests, list each one.\n"
    "3) Starting on the next line, write the post body: ONE short, self-contained piece (40-90 words) "
    "packed with information. It should feel like a 'banger' insight from a domain expert.\n"
    "The title must preview the specific information inside; do not use generic labels. "
    "Do not repeat 'TITLE' or the headline inside the body. Do not repeat 'TAGS' or any tag inside the body. "
    "Avoid hashtags, emoji, and filler words like 'interestingly' or 'surprisingly'. "
    "Get straight to the point. Do not greet the reader. Do not mention you are an AI."
)

_DEEP_DIVE_SYSTEM = (
    "You are the voice of Omakase. The user just read a short post and wants "
    "to go deeper into the topic. Your job is to expand with fascinating "
    "detail they didn't know about.\n\n"
    "OUTPUT FORMAT (strictly follow):\n"
    "Line 1: TITLE: <a compelling new headline for this deep dive>\n"
    "Line 2: TAGS: <comma-separated relevant tags>\n"
    "Lines 3+: The deep-dive body (150-250 words).\n\n"
    "RULES:\n"
    "- Reveal layers, history, mechanics, or controversy the original post only hinted at.\n"
    "- Do NOT repeat the original post's content verbatim.\n"
    "- No emoji, no hashtags, no filler phrases, no greetings.\n"
    "- Write as a knowledgeable friend, not a textbook."
)


def _feed_language_instruction(language: str) -> str:
    """Tells the model which natural language to use for TITLE line, TAGS line, and body."""
    if language == "tr":
        return (
            "LANGUAGE: Write the entire post in Turkish (Türkçe). "
            "Both the TITLE: headline (after the prefix TITLE: ) and every word of the body must be Turkish. "
            "Keep the literal ASCII prefixes TITLE: and TAGS: on their respective lines. "
            "The tag values after TAGS: must match the user's original interest strings exactly (do not translate them)."
        )
    return (
        "LANGUAGE: Write the entire post in English. "
        "Both the TITLE: headline (after the prefix TITLE: ) and the body must be English. "
        "Keep the literal ASCII prefixes TITLE: and TAGS: on their respective lines."
    )


def _feed_system_instruction(language: str) -> str:
    return SYSTEM_PROMPT + "\n\n" + _feed_language_instruction(language)

# Rotating format templates. The user prompt picks one based on seen_count so
# back-to-back posts always feel structurally different.
_POST_FORMATS = [
    (
        "FUN FACT DROP",
        "Share one genuinely surprising, little-known fact related to the user's interests. "
        "Start with the fact itself — don't say 'Fun fact:'. Make it feel like you just "
        "couldn't help sharing it. End with a punchy one-liner observation.",
    ),
    (
        "NICHES & NUANCE",
        "Explain a specific, non-obvious mechanism, technical rule, or historical nuance "
        "within the user's interest space. Avoid 'vibe-based' descriptions; provide "
        "the structural 'how' or 'why' that only an enthusiast would know.",
    ),
    (
        "UNLIKELY CONNECTION",
        "Find a surprising, counterintuitive connection between two things in the user's interest world. "
        "The weirder and more accurate the link, the better. Make the reader think 'wait, really?'",
    ),
    (
        "TINY RECOMMENDATION",
        "Give one very specific recommendation (a scene, a chapter, a moment, a dish, a technique, "
        "a detail) that most people overlook. Be precise enough that it feels like insider knowledge.",
    ),
    (
        "REFRAME",
        "Take something familiar from the user's interests and show it from a completely unexpected angle. "
        "Flip the conventional wisdom. The reader should feel like they'll never see it the same way again.",
    ),
    (
        "THE THING NOBODY TALKS ABOUT",
        "Surface an underrated, overlooked, or unfairly forgotten thing — a person, work, moment, or idea — "
        "related to the user's interests. Write with genuine enthusiasm, like you're righting a wrong.",
    ),
    (
        "CURSED TRIVIA",
        "Share a piece of trivia that is so odd, ironic, or absurd that it's almost offensive to know. "
        "Keep it true and accurate. Write with dry humor.",
    ),
    (
        "DEBATE",
        "Present two opposing sides of a topic related to the user's interests. "
        "Label them SIDE A and SIDE B. Keep each side to 2-3 sentences. "
        "Don't pick a winner—let the reader decide.",
    ),
    (
        "TIMELINE",
        "Create a mini chronological timeline (3-4 key moments) about something "
        "related to the user's interests. Use years or dates as anchors. Each "
        "entry is one punchy sentence.",
    ),
    (
        "VERSUS",
        "Compare two related things (X vs Y) from the user's interest space. "
        "2-3 sharp contrasts. No filler, no 'both are great' cop-outs.",
    ),
    (
        "MYTHBUSTER",
        "Take a widely believed 'fact' related to the user's interests and "
        "debunk it. State the myth clearly, then the reality. Be specific "
        "with evidence.",
    ),
    (
        "IF_YOU_LIKE_X_TRY_Y",
        "Based on one of the user's interests, recommend something unexpected "
        "from a completely different domain that shares a hidden quality. "
        "Explain the connection in 1-2 sentences.",
    ),
]


def _build_user_prompt(
    interests: list[str],
    seen_count: int,
    language: str,
    letterboxd_films: Optional[list[dict]] = None,
) -> str:
    cleaned = [i.strip() for i in interests if i and i.strip()]
    if not cleaned:
        taste = "someone with eclectic, thoughtful taste in culture"
    else:
        taste = "someone who cares about: " + ", ".join(cleaned)

    format_name, format_instruction = _POST_FORMATS[seen_count % len(_POST_FORMATS)]

    follow_lang = ""
    if language == "tr":
        follow_lang = (
            "Uyarı: Gönderiyi mutlaka Türkçe yaz. Aşağıdaki İngilizce format adı ve talimatlar "
            "sadece yapı için; çıktı tamamen Türkçe olmalı.\n\n"
        )

    # Letterboxd context — inject recently watched films when available.
    letterboxd_ctx = ""
    if letterboxd_films:
        film_lines: list[str] = []
        for f in letterboxd_films:  # include all films
            line = f.get("title", "Unknown")
            if f.get("year"):
                line += f" ({f['year']})"
            if f.get("rating"):
                line += f" — rated {f['rating']}/5"
            film_lines.append(line)
        letterboxd_ctx = (
            "\n\nLETTERBOXD CONTEXT: The user recently watched these films on Letterboxd "
            "(most recent first). Use this viewing history to make the post more relevant — "
            "draw connections, reference directors/genres they clearly enjoy, or surface "
            "interesting trivia about these specific films:\n"
            + "\n".join(f"  • {fl}" for fl in film_lines)
            + "\nCRITICAL: If you write about a specific film from this list, YOU MUST include its exact title in the TAGS line."
            + "\n"
        )

    return (
        follow_lang
        + f"Write a post for {taste}.\n"
        f"Post index in this session: {seen_count}.\n"
        f"\nFORMAT THIS POST AS: {format_name}\n"
        f"Instructions for this format: {format_instruction}\n"
        "\nThe post must feel human, specific, and entertaining — never generic or lecture-y. "
        "Do NOT label the format in the post itself."
        + letterboxd_ctx
    )


_TITLE_LINE = re.compile(r"(?i)^TITLE:\s*(.+)$")
_TAGS_LINE = re.compile(r"(?i)^TAGS:\s*(.+)$")


# Gemini often emits the entire post body in one stream delta. Clients expect multiple small
# `token` SSE events so the Swift UI can animate like Gemini in the browser.
_SPLIT_STREAM_SOFT_CAP = 6

# Artificial delay (seconds) inserted between SSE token events to create a smooth
# typing cadence on the client. Without this, tokens that arrive in a burst from
# the model are flushed all at once and the UI "jumps" instead of streaming.
_TOKEN_DRIP_DELAY = 0.045


def _split_fragment_for_smooth_stream(fragment: str, *, max_piece: int = _SPLIT_STREAM_SOFT_CAP) -> list[str]:
    """Split large model deltas into modest substrings, preferring word boundaries."""
    if not fragment:
        return []
    if len(fragment) <= max_piece:
        return [fragment]
    chunks: list[str] = []
    idx = 0
    fragment_len = len(fragment)
    min_wordish = max(2, max_piece // 6)
    while idx < fragment_len:
        end = min(idx + max_piece, fragment_len)
        if end >= fragment_len:
            tail = fragment[idx:]
            if tail:
                chunks.append(tail)
            break
        window = fragment[idx:end]
        cut = window.rfind(" ")
        if cut >= min_wordish:
            end = idx + cut + 1
        chunks.append(fragment[idx:end])
        idx = end
    return chunks if chunks else [fragment]


def _enqueue_stream_body_fragment(
    loop: asyncio.AbstractEventLoop,
    queue: asyncio.Queue,
    fragment: str,
) -> None:
    for piece in _split_fragment_for_smooth_stream(fragment):
        loop.call_soon_threadsafe(queue.put_nowait, ("token", piece))


def _feed_tokens_from_stream_chunks(response: object, queue: asyncio.Queue, loop: asyncio.AbstractEventLoop) -> None:
    """Turn Gemini stream chunks into queue items.

    Emits ('title', str), then ('tags', list[str]), then body ('token', str) events.
    """
    carry = ""
    title_done = False
    tags_done = False
    for chunk in response:
        text = _stream_chunk_text(chunk)
        if not text:
            continue
        carry += text
        if not title_done:
            if "\n" not in carry:
                continue
            first_line, carry = carry.split("\n", 1)
            m = _TITLE_LINE.match(first_line.strip())
            if m:
                loop.call_soon_threadsafe(
                    queue.put_nowait,
                    ("title", m.group(1).strip()),
                )
            else:
                carry = first_line + "\n" + carry
            title_done = True
        if title_done and not tags_done:
            if "\n" not in carry:
                continue
            second_line, rest = carry.split("\n", 1)
            mt = _TAGS_LINE.match(second_line.strip())
            if mt:
                raw_tags = [t.strip() for t in mt.group(1).split(",") if t.strip()]
                loop.call_soon_threadsafe(
                    queue.put_nowait,
                    ("tags", raw_tags),
                )
                carry = rest
            else:
                # Model didn't produce a TAGS line — put the line back.
                carry = second_line + "\n" + rest
            tags_done = True
        if carry:
            _enqueue_stream_body_fragment(loop, queue, carry)
            carry = ""
    if not title_done and carry:
        loop.call_soon_threadsafe(queue.put_nowait, ("token", carry))
    elif title_done and carry:
        _enqueue_stream_body_fragment(loop, queue, carry)


def _stream_chunk_text(chunk: object) -> str:
    """Best-effort text from a streaming chunk (Gemini SDK quirks vary by chunk)."""
    try:
        t = getattr(chunk, "text", None)
        if t:
            return str(t)
    except (ValueError, AttributeError):
        pass
    try:
        cands = getattr(chunk, "candidates", None) or []
        if not cands:
            return ""
        content = getattr(cands[0], "content", None)
        parts = getattr(content, "parts", None) if content is not None else None
        if not parts:
            return ""
        pieces: list[str] = []
        for part in parts:
            txt = getattr(part, "text", None)
            if txt:
                pieces.append(str(txt))
        return "".join(pieces)
    except (IndexError, AttributeError, TypeError):
        return ""


def _sse_event(data: dict, *, event: str | None = None) -> str:
    """Format a payload as a single SSE frame."""
    lines: list[str] = []
    if event:
        lines.append(f"event: {event}")
    lines.append(f"data: {json.dumps(data, ensure_ascii=False)}")
    lines.append("")
    lines.append("")
    return "\n".join(lines)


async def _stream_post(
    interests: list[str],
    seen_count: int,
    language: str,
    letterboxd_films: Optional[list[dict]] = None,
) -> AsyncIterator[str]:
    """Yield SSE frames for one generated post."""
    post_id = str(uuid.uuid4())
    yield _sse_event({"id": post_id}, event="start")

    # Emit the format name so the iOS client can show a visual badge.
    format_name, _ = _POST_FORMATS[seen_count % len(_POST_FORMATS)]
    yield _sse_event({"format": format_name}, event="format")

    if not GEMINI_API_KEY:
        yield _sse_event(
            {"message": "Server is missing GEMINI_API_KEY. See backend/README.md."},
            event="error",
        )
        return

    prompt = _build_user_prompt(interests, seen_count, language, letterboxd_films=letterboxd_films)

    try:
        # The genai SDK's streaming API is synchronous; run it in a
        # worker thread and bridge each chunk to the async generator.
        queue: asyncio.Queue[tuple[str, object]] = asyncio.Queue()
        loop = asyncio.get_running_loop()

        def _produce() -> None:
            try:
                response = genai_client.models.generate_content_stream(
                    model=GEMINI_MODEL,
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        system_instruction=_feed_system_instruction(language),
                        thinking_config=types.ThinkingConfig(thinking_budget=0)
                    )
                )
                _feed_tokens_from_stream_chunks(response, queue, loop)
                loop.call_soon_threadsafe(queue.put_nowait, ("done", None))
            except Exception as exc:  # noqa: BLE001 — funnel any SDK error to the client
                loop.call_soon_threadsafe(queue.put_nowait, ("error", exc))

        producer = asyncio.create_task(asyncio.to_thread(_produce))

        saw_any_output = False
        saw_error = False
        while True:
            kind, payload = await queue.get()
            if kind == "token":
                saw_any_output = True
                yield _sse_event({"text": payload}, event="token")
                # Drip-feed tokens so the client sees a gradual typing effect
                # even when Gemini dumps the entire response in one burst.
                # The sleep *alone* isn't enough — Starlette can still batch
                # successive small yields into a single HTTP chunk. The SSE
                # comment (`:flush`) is harmless per spec but adds enough
                # bytes so the transport layer pushes the data immediately.
                yield ": flush\n\n"
                await asyncio.sleep(_TOKEN_DRIP_DELAY)
            elif kind == "title":
                saw_any_output = True
                yield _sse_event({"title": str(payload)}, event="title")
            elif kind == "tags":
                saw_any_output = True
                final_tags = list(payload)
                if letterboxd_films:
                    # Prepend "Letterboxd" tag if not already generated
                    if "Letterboxd" not in final_tags:
                        final_tags.insert(0, "Letterboxd")
                yield _sse_event({"tags": final_tags}, event="tags")
            elif kind == "done":
                break
            elif kind == "error":
                saw_error = True
                logger.exception("Gemini streaming failed", exc_info=payload)
                yield _sse_event({"message": str(payload)}, event="error")
                break

        await producer

        if not saw_any_output and not saw_error:
            yield _sse_event(
                {
                    "message": (
                        "The model returned no text. Check GEMINI_MODEL in .env "
                        f"(currently {GEMINI_MODEL!r}), API quota, and that the key is valid."
                    )
                },
                event="error",
            )

    except asyncio.CancelledError:
        # Client disconnected — just stop.
        logger.info("Client disconnected from stream %s", post_id)
        raise

    yield _sse_event({"id": post_id}, event="done")


def _build_deep_dive_prompt(req: DeepDiveRequest) -> str:
    lang_note = ""
    if req.language == "tr":
        lang_note = (
            "\n\nIMPORTANT: Write the TITLE value and body in Turkish. "
            "Keep the ASCII prefixes TITLE: and TAGS: in English."
        )
    return (
        f"The user's interests: {', '.join(req.interests)}\n\n"
        f"ORIGINAL POST TITLE: {req.original_title}\n"
        f"ORIGINAL POST BODY:\n{req.original_text}\n\n"
        f"Now write a deep-dive expanding on this topic."
        f"{lang_note}"
    )


async def _stream_deep_dive(req: DeepDiveRequest) -> AsyncIterator[str]:
    """Yield SSE frames for a deep-dive expansion of an existing post."""
    post_id = str(uuid.uuid4())
    yield _sse_event({"id": post_id}, event="start")

    if not GEMINI_API_KEY:
        yield _sse_event(
            {"message": "Server is missing GEMINI_API_KEY. See backend/README.md."},
            event="error",
        )
        return

    system = _DEEP_DIVE_SYSTEM + "\n\n" + _feed_language_instruction(req.language)
    prompt = _build_deep_dive_prompt(req)

    try:
        queue: asyncio.Queue[tuple[str, object]] = asyncio.Queue()
        loop = asyncio.get_running_loop()

        def _produce() -> None:
            try:
                response = genai_client.models.generate_content_stream(
                    model=GEMINI_DEEP_DIVE_MODEL,
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        system_instruction=system,
                        thinking_config=types.ThinkingConfig(thinking_budget=0)
                    )
                )
                _feed_tokens_from_stream_chunks(response, queue, loop)
                loop.call_soon_threadsafe(queue.put_nowait, ("done", None))
            except Exception as exc:  # noqa: BLE001
                loop.call_soon_threadsafe(queue.put_nowait, ("error", exc))

        producer = asyncio.create_task(asyncio.to_thread(_produce))

        saw_any_output = False
        saw_error = False
        while True:
            kind, payload = await queue.get()
            if kind == "token":
                saw_any_output = True
                yield _sse_event({"text": payload}, event="token")
                yield ": flush\n\n"
                await asyncio.sleep(_TOKEN_DRIP_DELAY)
            elif kind == "title":
                saw_any_output = True
                yield _sse_event({"title": str(payload)}, event="title")
            elif kind == "tags":
                saw_any_output = True
                yield _sse_event({"tags": payload}, event="tags")
            elif kind == "done":
                break
            elif kind == "error":
                saw_error = True
                logger.exception("Gemini deep-dive streaming failed", exc_info=payload)
                yield _sse_event({"message": str(payload)}, event="error")
                break

        await producer

        if not saw_any_output and not saw_error:
            yield _sse_event(
                {
                    "message": (
                        "The model returned no text. Check GEMINI_MODEL in .env "
                        f"(currently {GEMINI_MODEL!r}), API quota, and that the key is valid."
                    )
                },
                event="error",
            )

    except asyncio.CancelledError:
        logger.info("Client disconnected from deep-dive stream %s", post_id)
        raise

    yield _sse_event({"id": post_id}, event="done")


def _generative_response_text(response: object) -> str:
    """Best-effort plain text from google-generativeai (handles blocked / multi-part replies)."""
    try:
        text = response.text  # type: ignore[attr-defined]
        if isinstance(text, str) and text.strip():
            return text.strip()
    except Exception:  # noqa: BLE001 — SDK raises if no parts / blocked
        pass
    candidates = getattr(response, "candidates", None) or []
    if not candidates:
        return ""
    parts_out: list[str] = []
    for cand in candidates:
        content = getattr(cand, "content", None)
        parts = getattr(content, "parts", None) if content is not None else None
        if not parts:
            continue
        for part in parts:
            t = getattr(part, "text", None)
            if isinstance(t, str) and t:
                parts_out.append(t)
    return "".join(parts_out).strip()


def _parse_suggestion_strings(raw: str) -> list[str]:
    """Parse model output into a list of suggestion strings (JSON array, with fallbacks)."""
    s = raw.strip()
    s = s.removeprefix("```json").removeprefix("```").removesuffix("```").strip()

    def _loads_list(payload: str) -> list[str]:
        data = json.loads(payload)
        if not isinstance(data, list):
            raise ValueError("Model did not return a JSON array.")
        return [str(x) for x in data if x]

    try:
        return _loads_list(s)
    except (json.JSONDecodeError, ValueError, TypeError):
        pass

    # Model wrapped the array in prose; take the first [...] block.
    start = s.find("[")
    end = s.rfind("]")
    if start != -1 and end > start:
        try:
            return _loads_list(s[start : end + 1])
        except (json.JSONDecodeError, ValueError, TypeError):
            pass

    # Last resort: double-quoted strings on their own lines.
    quoted = re.findall(r'"([^"\\]*(?:\\.[^"\\]*)*)"', s)
    if len(quoted) >= 3:
        return quoted[:10]

    raise ValueError(f"Could not parse suggestions from model output (first 200 chars): {s[:200]!r}")


_SUGGEST_SYSTEM = (
    "You are an interest-discovery assistant. Given a list of things a user already cares about "
    "(and optionally a partial search term they are typing), suggest NEW interests they might enjoy. "
    "Follow these rules strictly:\n"
    "1. Return ONLY a JSON array of strings — no markdown, no explanation, no extra keys.\n"
    "2. Return exactly 7 suggestions.\n"
    "3. About 4 of the 7 should be closely related to what the user already listed.\n"
    "4. The remaining 3 should be surprising, lateral, or from an adjacent domain — things the user "
    "probably hasn't considered but might love once they discover them.\n"
    "5. Never repeat an interest the user already has, nor any item listed as an excluded suggestion.\n"
    "6. Keep each suggestion short: 1-4 words, title-cased.\n"
    "7. Prioritise specificity over genre labels (e.g. prefer 'Wong Kar-wai' over 'Arthouse Cinema')."
)


def _suggest_system_for_language(language: str) -> str:
    lang_rule = (
        "8. Write all 7 strings in natural Turkish (Türkçe), using culturally normal spelling and "
        "title-style capitalization suitable for Turkish."
        if language == "tr"
        else "8. Write all 7 strings in English."
    )
    return _SUGGEST_SYSTEM + "\n" + lang_rule


@app.post("/interests/suggest")
async def interests_suggest(req: SuggestRequest) -> dict:
    """Return ~7 AI-generated interest suggestions based on what the user already has.

    Response: ``{ "suggestions": ["...", ...] }``
    """
    if not GEMINI_API_KEY:
        raise HTTPException(status_code=503, detail="Server is missing GEMINI_API_KEY.")

    existing = [i.strip() for i in req.interests if i.strip()]
    draft = req.draft.strip()
    excluded = [s.strip() for s in req.exclude_suggestions if s.strip()]

    parts: list[str] = []
    if existing:
        parts.append("Interests already added: " + ", ".join(existing) + ".")
    if draft:
        parts.append(f'The user is currently typing: "{draft}".  '
                     "Include suggestions related to this term as well.")
    if not parts:
        parts.append("The user hasn't added any interests yet. Suggest a diverse, intriguing starter set.")
    if excluded:
        parts.append(
            "These ideas were already shown — suggest 7 completely different ones (do not repeat or "
            "minorly rephrase): " + ", ".join(excluded) + "."
        )

    lang_code = req.language

    user_prompt = " ".join(parts) + "\n\nRespond with a JSON array only."

    try:
        response = await asyncio.to_thread(
            genai_client.models.generate_content,
            model=GEMINI_SUGGEST_MODEL,
            contents=user_prompt,
            config=types.GenerateContentConfig(
                system_instruction=_suggest_system_for_language(lang_code),
                thinking_config=types.ThinkingConfig(thinking_budget=0)
            )
        )
        raw = _generative_response_text(response)
        if not raw:
            fr = None
            if getattr(response, "candidates", None):
                fr = getattr(response.candidates[0], "finish_reason", None)
            logger.warning("Interest suggestion: empty model text (finish_reason=%s)", fr)
            raise ValueError("Model returned no text (blocked, empty, or unsupported response).")
        suggestions = _parse_suggestion_strings(raw)[:10]
    except Exception as exc:  # noqa: BLE001
        logger.warning("Interest suggestion failed: %s", exc)
        raise HTTPException(status_code=502, detail=f"Suggestion generation failed: {exc}") from exc

    return {"suggestions": suggestions}


@app.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok", "model": GEMINI_MODEL, "has_api_key": str(bool(GEMINI_API_KEY))}


@app.post("/feed/stream")
async def feed_stream(req: FeedRequest) -> StreamingResponse:
    """Stream a single generated post as Server-Sent Events.

    The response is `text/event-stream` with event types:

    - `start` — `{ "id": "<uuid>" }` signals a new post
    - `title` — `{ "title": "<headline>" }` once, parsed from the model's `TITLE:` line
    - `token` — `{ "text": "<delta>" }` for each body chunk (title line is not repeated here)
    - `done`  — `{ "id": "<uuid>" }` signals the post is complete

    On failure an `error` event is emitted with a human-readable message.
    """
    if len(req.interests) > 50:
        raise HTTPException(status_code=400, detail="Too many interests (max 50).")

    headers = {
        "Cache-Control": "no-cache",
        "Connection": "keep-alive",
        # Disable buffering on common reverse proxies.
        "X-Accel-Buffering": "no",
    }
    return StreamingResponse(
        _stream_post(
            req.interests,
            req.seen_count,
            req.language,
            letterboxd_films=req.letterboxd_films,
        ),
        media_type="text/event-stream",
        headers=headers,
    )


@app.post("/feed/deep-dive")
async def deep_dive(req: DeepDiveRequest):
    """Stream a deep-dive expansion of an existing post as Server-Sent Events.

    The response is `text/event-stream` with the same event types as `/feed/stream`.
    """
    return StreamingResponse(
        _stream_deep_dive(req),
        media_type="text/event-stream",
        headers={"X-Accel-Buffering": "no", "Cache-Control": "no-cache"},
    )


# ---------------------------------------------------------------------------
# Letterboxd RSS parsing
# ---------------------------------------------------------------------------

_LETTERBOXD_NS = {
    "letterboxd": "https://letterboxd.com",
    "tmdb": "https://themoviedb.org",
    "dc": "http://purl.org/dc/elements/1.1/",
}


class LetterboxdFilmsRequest(BaseModel):
    """Payload for fetching a user's recent films from Letterboxd."""
    username: str = Field(..., min_length=1, max_length=100)
    limit: int = Field(default=20, ge=1, le=20)


def _parse_letterboxd_rss(xml_bytes: bytes, *, limit: int = 5) -> list[dict]:
    """Parse Letterboxd RSS XML into a list of film dicts."""
    root = ET.fromstring(xml_bytes)
    channel = root.find("channel")
    if channel is None:
        return []

    films: list[dict] = []
    for item in channel.findall("item"):
        title = item.findtext("{https://letterboxd.com}filmTitle", "")
        if not title:
            # Fall back to <title> and strip the rating suffix.
            raw_title = item.findtext("title", "")
            title = re.sub(r"\s*,\s*\d{4}\s*-\s*★.*$", "", raw_title).strip()
        year = item.findtext("{https://letterboxd.com}filmYear", "")
        rating = item.findtext("{https://letterboxd.com}memberRating", "")
        watched = item.findtext("{https://letterboxd.com}watchedDate", "")

        films.append({
            "title": title,
            "year": int(year) if year and year.isdigit() else None,
            "rating": float(rating) if rating else None,
            "watched_date": watched or None,
        })
        if len(films) >= limit:
            break
    return films


@app.post("/letterboxd/films")
async def letterboxd_films(req: LetterboxdFilmsRequest) -> dict:
    """Fetch a user's recently watched films from their Letterboxd RSS feed.

    Response: ``{ "films": [...], "username": "..." }``
    """
    rss_url = f"https://letterboxd.com/{req.username}/rss/"
    logger.info("Fetching Letterboxd RSS for user %r", req.username)

    def _fetch() -> bytes:
        request = Request(
            rss_url,
            headers={
                "User-Agent": "Omakase/1.0 (https://github.com/omakase-app)",
                "Accept": "application/rss+xml, application/xml, text/xml",
            },
        )
        try:
            with urlopen(request, timeout=10) as resp:
                return resp.read()
        except HTTPError as exc:
            if exc.code == 404:
                raise ValueError(f"Letterboxd user '{req.username}' not found.") from exc
            raise ValueError(f"Letterboxd returned HTTP {exc.code}.") from exc
        except URLError as exc:
            raise ValueError(f"Could not reach Letterboxd: {exc.reason}") from exc

    try:
        xml_bytes = await asyncio.to_thread(_fetch)
        films = _parse_letterboxd_rss(xml_bytes, limit=req.limit)
    except ValueError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    except Exception as exc:  # noqa: BLE001
        logger.warning("Letterboxd fetch failed: %s", exc)
        raise HTTPException(status_code=502, detail=f"Failed to fetch Letterboxd data: {exc}") from exc

    return {"films": films, "username": req.username}
